### ISSUE TITLE
Tests for the project are packaged and distributed

### ISSUE THREAD

**Issue by facundobatista** [albertodonato/snap-helpers#2]
The tests for the project itself are being packaged and distributed. This is normally avoided as it just bloats the package and waste resources (bandwidth, disk usage, time) in all installations.

One easy way to fix it is to move the `tests` directory out of `snaphelpers` directory, to the root of the project.

Thanks!

**Comment by albertodonato** [comment]
Thanks. Fixed by https://github.com/albertodonato/snap-helpers/commit/614670f0bfcc8cc4ec45b8abb1127cabb1c207a2 (despite wrong reference in commit message)

**Comment by facundobatista** [comment]
Thank you!
